# Generated by Django 5.0.6 on 2024-06-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_coupon',
            field=models.CharField(default='5783D88C', max_length=50),
        ),
    ]

