# Generated by Django 5.0.6 on 2024-06-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_homepage', '0004_alter_product_discount_coupon_orderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_coupon',
            field=models.CharField(default='05CE2A37', max_length=50),
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
