# Generated by Django 5.0.6 on 2024-06-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_homepage', '0005_alter_product_discount_coupon_delete_orderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_coupon',
            field=models.CharField(default='E189C6C9', max_length=50),
        ),
    ]
