# Generated by Django 5.0.6 on 2024-06-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_homepage', '0007_remove_category_status_remove_category_trending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=False, help_text='0=default,1=Hidden'),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False, help_text='0=default,1=Hidden'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_coupon',
            field=models.CharField(default='5ED57206', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
