# Generated by Django 5.0.6 on 2024-06-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_homepage', '0008_category_status_product_number_of_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_coupon',
            field=models.CharField(default='92871412', max_length=50),
        ),
    ]
