# Generated by Django 5.0.6 on 2024-06-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_homepage', '0009_alter_product_discount_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image1',
            field=models.ImageField(default=0, upload_to='photos/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image2',
            field=models.ImageField(default=0, upload_to='photos/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image3',
            field=models.ImageField(default=0, upload_to='photos/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_coupon',
            field=models.CharField(default='0B46E6B6', max_length=50),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
