# Generated by Django 5.0.6 on 2024-06-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_homepage', '0011_alter_product_discount_coupon_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_coupon',
            field=models.CharField(default='39411E57', max_length=50),
        ),
    ]
