# Generated by Django 5.0.6 on 2024-06-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_variations'),
        ('user_homepage', '0013_alter_product_discount_coupon_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_coupon',
            field=models.CharField(default='27C1BEF8', max_length=50),
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
