# Generated by Django 5.0.6 on 2024-06-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_account', '0002_user_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
